### ISSUE TITLE
TestKeepAlive is flaky

### ISSUE THREAD

**Issue by xqrzd** [xqrzd/kudu-client-net#143]
This test has failed in a couple different places,

```
[xUnit.net 00:00:10.61]     Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive [FAIL]
  X Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive [9s 533ms]
  Error Message:
   System.Exception : Scanner has already been closed
  Stack Trace:
     at Knet.Kudu.Client.KuduScanEnumerator`1.KeepAliveAsync(CancellationToken cancellationToken) in /home/runner/work/kudu-client-net/kudu-client-net/src/Knet.Kudu.Client/KuduScanEnumerator.cs:line 277
   at Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive() in /home/runner/work/kudu-client-net/kudu-client-net/test/Knet.Kudu.Client.FunctionalTests/ScannerTests.cs:line 195
   at Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive() in /home/runner/work/kudu-client-net/kudu-client-net/test/Knet.Kudu.Client.FunctionalTests/ScannerTests.cs:line 227
   at Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive() in /home/runner/work/kudu-client-net/kudu-client-net/test/Knet.Kudu.Client.FunctionalTests/ScannerTests.cs:line 227
--- End of stack trace from previous location where exception was thrown ---
```

```
[xUnit.net 00:00:46.96]     Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive [FAIL]
  Failed Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive [45 s]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive() in /home/runner/work/kudu-client-net/kudu-client-net/test/Knet.Kudu.Client.FunctionalTests/ScannerTests.cs:line 199
   at Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive() in /home/runner/work/kudu-client-net/kudu-client-net/test/Knet.Kudu.Client.FunctionalTests/ScannerTests.cs:line 227
   at Knet.Kudu.Client.FunctionalTests.ScannerTests.TestKeepAlive() in /home/runner/work/kudu-client-net/kudu-client-net/test/Knet.Kudu.Client.FunctionalTests/ScannerTests.cs:line 227
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by xqrzd** [comment]
This was fixed by updating the scanner in the test to use the read mode 'read your own writes'.
